/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author vic
 */
public class AbonoCreditoCliente extends javax.swing.JFrame {

    /**
     * Creates new form AbonoCreditoCliente
     */
    public AbonoCreditoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigoEntrada = new javax.swing.JTextField();
        txtDescripcionEntrada = new javax.swing.JTextField();
        txtCantidadEntrada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCodigoEntrada.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtCodigoEntrada.setText("Abona $");
        txtCodigoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoEntradaActionPerformed(evt);
            }
        });
        txtCodigoEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoEntradaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoEntradaKeyTyped(evt);
            }
        });

        txtDescripcionEntrada.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtDescripcionEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionEntradaKeyTyped(evt);
            }
        });

        txtCantidadEntrada.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtCantidadEntrada.setText("1");
        txtCantidadEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadEntradaActionPerformed(evt);
            }
        });
        txtCantidadEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadEntradaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadEntradaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadEntradaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(txtCodigoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDescripcionEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(txtCantidadEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcionEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(278, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoEntradaActionPerformed

    private void txtCodigoEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoEntradaKeyPressed

        //codigo que llama al producto llena campo codigo,descripcion, cantidad, precio y stock
       // if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
         //   if (!"".equals(txtCodigoEntrada.getText())) {
           //     String cod = txtCodigoEntrada.getText();
               // pro = proDao.BuscarPro(cod);
                //if (pro.getNombre() != null) {
                  //  txtIdPro.setText("" + pro.getId());
                    //txtDescripcionEntrada.setText("" + pro.getNombre());
                    //txtPrecioEntrada.setText("" + pro.getPrecio());
                    //txtStockDisponible1.setText("" + pro.getStock());
                    //txtCantidadEntrada.requestFocus();
                //} else {
                  //  LimpiarEntrada();

                    //txtCodigoEntrada.requestFocus();
                    //JOptionPane.showMessageDialog(null, "EL CODIGO DE PRODUCTO NO EXISTE");
               // }
            //} else {
              //  JOptionPane.showMessageDialog(null, "Ingrese el codigo del productos");
                //txtCodigoEntrada.requestFocus();
                //LimpiarEntrada();
            //}
        //}

        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoEntradaKeyPressed

    private void txtCodigoEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoEntradaKeyTyped

      //  event.numberKeyPress(evt);

        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoEntradaKeyTyped

    private void txtDescripcionEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionEntradaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionEntradaKeyTyped

    private void txtCantidadEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadEntradaActionPerformed
        //LimpiarEntrada();        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadEntradaActionPerformed

    private void txtCantidadEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadEntradaKeyPressed
        // TODO add your handling code here:

       // if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            //si el campo tiene un nuemero
            //if (!"".equals(txtCantidadEntrada.getText())) {
         //       if (!"".equals(txtCantidadEntrada.getText())) {
           //         int id = Integer.parseInt(txtIdPro.getText());
             //       String descripcion = txtDescripcionEntrada.getText();
               //     int cant = Integer.parseInt(txtCantidadEntrada.getText());
                 //   double precio = Double.parseDouble(txtPrecioEntrada.getText());
                   // double total = cant * precio;
                    //int stock = Integer.parseInt(txtStockDisponible1.getText());
                    // aqui le digo que no importa si el producto ingresado es mayor o menor al stock
                   // stock = 0;
                    //if (stock != cant) {

                        // !=  >=   38 != 50 esto estaba antes no dejaba meter una entrada mayor al stock
                      //  item = item + 1;
                        //tmp = (DefaultTableModel) TableEntrada.getModel();
                        //for (int i = 0; i < TableEntrada.getRowCount(); i++) {
                          //  if (TableEntrada.getValueAt(i, 1).equals(txtDescripcionEntrada.getText())) {
                                //JOptionPane.showMessageDialog(null, "El producto ya esta registrado");
                                //LimpiarEntrada();
                                //txtCodigoEntrada.requestFocus();
                                //return;

                            //}
                        //}
                        //ArrayList lista = new ArrayList();
                        //lista.add(item);
                        //lista.add(id);
                        //lista.add(descripcion);
                        //lista.add(cant);
                        //lista.add(precio);
                        //lista.add(total);
                        //Object[] O = new Object[5];
                        //O[0] = lista.get(1);
                        //O[1] = lista.get(2);
                        //O[2] = lista.get(3);
                        //O[3] = lista.get(4);
                        //O[4] = lista.get(5);
                        //tmp.addRow(O);
                        //TableEntrada.setModel(tmp);
                        //LimpiarEntrada();
                        //TotalPagarEntrada();
                        //LimparVenta();

                        //txtCodigoEntrada.requestFocus();

                    //} else {
                      //  JOptionPane.showMessageDialog(null, "Stock no disponible");

                    //}
                //} else {
                  //  JOptionPane.showMessageDialog(null, "Ingrese cantidad");
                //}
           // }
    }//GEN-LAST:event_txtCantidadEntradaKeyPressed

    private void txtCantidadEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadEntradaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadEntradaKeyReleased

    private void txtCantidadEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadEntradaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadEntradaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbonoCreditoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbonoCreditoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbonoCreditoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbonoCreditoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbonoCreditoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtCantidadEntrada;
    private javax.swing.JTextField txtCodigoEntrada;
    private javax.swing.JTextField txtDescripcionEntrada;
    // End of variables declaration//GEN-END:variables
}
