/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Cliente;
import Modelo.ClienteDao;
import Modelo.Conexion;
import Modelo.Detalle;
import Modelo.Productos;
import Modelo.ProductosDao;
import Modelo.Venta;
import Modelo.VentaDao;
import static Vista.Sistema.LabelVendedor;
import static Vista.Sistema.TableCreditClient;
import static Vista.Sistema.TableVenta;
import static Vista.Sistema.jTabbedPane1;
import static Vista.Sistema.txtCodigoVenta;
import static Vista.Sistema.txtCodigoVentaCreditClient;
import static Vista.Sistema.txtIdCV;
import static Vista.Sistema.txtNombreClienteventaCredit;
import static Vista.Sistema.txtRucVentaCredit;
import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vic
 */
public class ConsultaCreditoCliente extends javax.swing.JFrame {
  
    
    private String dato;
     private String nombreCliente;
      Date fechaVenta = new Date();
     String fechaActual = new SimpleDateFormat("dd/MM/yyyy").format(fechaVenta);
    
    
        Connection con;
    Conexion cn = new Conexion();
    PreparedStatement ps;
    ResultSet rs;
    DefaultTableModel modelo = new DefaultTableModel(); 
     Cliente cl = new Cliente();
    ClienteDao client = new ClienteDao();
    VentaDao Vdao = new VentaDao();
      Detalle Dv = new Detalle();
          Venta v = new Venta();
    DefaultTableModel tmp = new DefaultTableModel();
  //TableRowSorter<DefaultTableModel>sorter;
  
   Productos pro = new Productos();
    ProductosDao proDao = new ProductosDao();
     String mayus;
      double TotalPagar = 0.00;
          double TotalpagarCredit= 0.00;
            double TotalPagarCreditos= 0.00;
    /**
     * Creates new form FrmBusqueda
     */
      
    public ConsultaCreditoCliente() {
        
        initComponents();
                //listar(); 
                TotalPagarX();

          //ListarProductos4();
           txtBuscar2.requestFocus();
          this.setLocationRelativeTo(null);
           txtCantidadVenta.setVisible(false);
           jLabel5.setVisible(false);
           
           //boton buscar
           jLabel52.setVisible(false);
           
               txtBuscar2.setVisible(false);
               btnGenerarVentaCredit.setVisible(false);
               btnEliminar.setVisible(false);
               txtRucVentaCredit2.setVisible(false);
               txtNombreClienteventaCredit.setVisible(false);
               btnCobrar.setVisible(false);
               jLabel59.setVisible(false);
                       jLabel58.setVisible(false);
    }
public void sedDato(String dato,String nombreCliente){


this.dato=dato;
this.nombreCliente=nombreCliente;

txtBuscar2.setText(dato);
lblNombreCliente.setText(nombreCliente);



} 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        TableConsultaCreditCliente = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtCantidadVenta = new javax.swing.JTextField();
        txtBuscar2 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        lblEnviaTotalCredit = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PrintBtn = new javax.swing.JButton();
        btnCobrar = new javax.swing.JButton();
        LabelVendedor = new javax.swing.JLabel();
        txtIdCV = new javax.swing.JTextField();
        btnGenerarVentaCredit = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        txtRucVentaCredit2 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        txtNombreClienteventaCredit = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("formKeyReleased"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        TableConsultaCreditCliente.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        TableConsultaCreditCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CODIGO", "DESCRIPCIÓN", "CANTIDAD", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableConsultaCreditCliente.setRowHeight(25);
        TableConsultaCreditCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableConsultaCreditClienteMouseClicked(evt);
            }
        });
        TableConsultaCreditCliente.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                TableConsultaCreditClienteCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        TableConsultaCreditCliente.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TableConsultaCreditClientePropertyChange(evt);
            }
        });
        TableConsultaCreditCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TableConsultaCreditClienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TableConsultaCreditClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TableConsultaCreditClienteKeyTyped(evt);
            }
        });
        jScrollPane8.setViewportView(TableConsultaCreditCliente);
        if (TableConsultaCreditCliente.getColumnModel().getColumnCount() > 0) {
            TableConsultaCreditCliente.getColumnModel().getColumn(0).setMinWidth(10);
            TableConsultaCreditCliente.getColumnModel().getColumn(0).setPreferredWidth(50);
            TableConsultaCreditCliente.getColumnModel().getColumn(0).setMaxWidth(50);
            TableConsultaCreditCliente.getColumnModel().getColumn(1).setMinWidth(50);
            TableConsultaCreditCliente.getColumnModel().getColumn(1).setPreferredWidth(100);
            TableConsultaCreditCliente.getColumnModel().getColumn(1).setMaxWidth(60);
            TableConsultaCreditCliente.getColumnModel().getColumn(2).setResizable(false);
            TableConsultaCreditCliente.getColumnModel().getColumn(2).setPreferredWidth(200);
            TableConsultaCreditCliente.getColumnModel().getColumn(3).setMinWidth(20);
            TableConsultaCreditCliente.getColumnModel().getColumn(3).setPreferredWidth(50);
            TableConsultaCreditCliente.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Cant");

        txtCantidadVenta.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCantidadVenta.setText("1");
        txtCantidadVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadVentaActionPerformed(evt);
            }
        });
        txtCantidadVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadVentaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadVentaKeyTyped(evt);
            }
        });

        txtBuscar2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar2ActionPerformed(evt);
            }
        });
        txtBuscar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscar2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscar2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscar2KeyTyped(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(51, 51, 255));
        jLabel52.setText("Buscar ");

        jLabel60.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/money.png"))); // NOI18N
        jLabel60.setText("Total :");

        lblEnviaTotalCredit.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        lblEnviaTotalCredit.setForeground(new java.awt.Color(51, 51, 255));
        lblEnviaTotalCredit.setText("-----");

        lblNombreCliente.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNombreCliente.setForeground(new java.awt.Color(255, 0, 0));
        lblNombreCliente.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CREDITO:");

        PrintBtn.setText("PDF Compartir");
        PrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBtnActionPerformed(evt);
            }
        });

        btnCobrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCobrar.setText("cobrar");
        btnCobrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCobrarMouseClicked(evt);
            }
        });
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });
        btnCobrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCobrarKeyPressed(evt);
            }
        });

        LabelVendedor.setForeground(new java.awt.Color(255, 255, 255));
        LabelVendedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelVendedor.setText("Vida Informatico");

        txtIdCV.setText("1");

        btnGenerarVentaCredit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/print.png"))); // NOI18N
        btnGenerarVentaCredit.setText("ACEPTAR");
        btnGenerarVentaCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarVentaCreditActionPerformed(evt);
            }
        });

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel58.setText("ID");

        txtRucVentaCredit2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtRucVentaCredit2.setText("1");
        txtRucVentaCredit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRucVentaCredit2ActionPerformed(evt);
            }
        });
        txtRucVentaCredit2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRucVentaCredit2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRucVentaCredit2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRucVentaCredit2KeyTyped(evt);
            }
        });

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel59.setText("Cliente:");

        txtNombreClienteventaCredit.setEditable(false);
        txtNombreClienteventaCredit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtNombreClienteventaCredit.setForeground(new java.awt.Color(51, 51, 255));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel58)
                .addGap(16, 16, 16)
                .addComponent(txtRucVentaCredit2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel59)
                .addGap(10, 10, 10)
                .addComponent(txtNombreClienteventaCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(658, 658, 658))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtIdCV, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(503, 503, 503)
                        .addComponent(btnGenerarVentaCredit)
                        .addGap(39, 39, 39)
                        .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(PrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEnviaTotalCredit))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(499, 499, 499)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(lblNombreCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel52)
                        .addGap(27, 27, 27)
                        .addComponent(txtBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtIdCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelVendedor)
                                .addGap(0, 51, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNombreCliente)
                                    .addComponent(jLabel1))
                                .addGap(8, 8, 8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel52)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(PrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel60)
                                    .addComponent(lblEnviaTotalCredit))))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel58))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(txtRucVentaCredit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel59))
                            .addComponent(txtNombreClienteventaCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarVentaCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(503, 503, 503))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableConsultaCreditClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableConsultaCreditClienteMouseClicked
    
    }//GEN-LAST:event_TableConsultaCreditClienteMouseClicked

    private void TableConsultaCreditClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableConsultaCreditClienteKeyPressed



        
        //este codigog desactiva la accion enter por defefault
        JTable jMyTable = new JTable();
jMyTable.addKeyListener(new java.awt.event.KeyAdapter() {
     public void keyPressed(java.awt.event.KeyEvent evt) {
         TableConsultaCreditClienteKeyPressed(evt);
     }
 });
        
        if(evt.getKeyCode() == evt.VK_ENTER){
         evt.consume();
         EnterBusqueda();
            txtCodigoVenta.requestFocus();
     }


    }//GEN-LAST:event_TableConsultaCreditClienteKeyPressed

    
       
    
    
    private void txtCantidadVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadVentaActionPerformed

    private void txtCantidadVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadVentaKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtCantidadVentaKeyPressed

    private void txtCantidadVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadVentaKeyTyped
        // TODO add your handling code here:
     //   event.numberKeyPress(evt);
    }//GEN-LAST:event_txtCantidadVentaKeyTyped

    private void txtBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar2ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar2ActionPerformed

    private void txtBuscar2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscar2KeyPressed
          this.setLocationRelativeTo(null);
     // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar2KeyPressed

    private void txtBuscar2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscar2KeyReleased

    // if (!"".equals(txtBuscar.getText())) {
        
     //}else
         
     //{
       //     } 
     

 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar2KeyReleased

    private void txtBuscar2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscar2KeyTyped

KeyboardFocusManager kb = KeyboardFocusManager.getCurrentKeyboardFocusManager();
kb.addKeyEventPostProcessor(new KeyEventPostProcessor(){
            public boolean postProcessKeyEvent(KeyEvent e){
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE && this != null){
                    System.out.println("probando...");
                    dispose();
                    return false;
                }
                return true;
            }
});       
     
    }//GEN-LAST:event_txtBuscar2KeyTyped

    private void TableConsultaCreditClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableConsultaCreditClienteKeyTyped

 //if(evt.getKeyCode() == evt.VK_ENTER){
   //      evt.consume();
     //}
int fila = TableConsultaCreditCliente.getSelectedRow();
      if(fila == -1){
          txtBuscar2.requestFocus();
     JOptionPane.showMessageDialog(null,"No se selecciono ningna fila");
        }else{
          // EnterBusqueda();      
        }            // TODO add your handling code here:
  
      
    }//GEN-LAST:event_TableConsultaCreditClienteKeyTyped

    private void TableConsultaCreditClientePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TableConsultaCreditClientePropertyChange
      // TODO add your handling code here:
    }//GEN-LAST:event_TableConsultaCreditClientePropertyChange

    private void TableConsultaCreditClienteCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TableConsultaCreditClienteCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TableConsultaCreditClienteCaretPositionChanged

    private void TableConsultaCreditClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableConsultaCreditClienteKeyReleased
       // TODO add your handling code here:
    }//GEN-LAST:event_TableConsultaCreditClienteKeyReleased

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

              // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
       // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
listar();   
TotalPagarX();
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void PrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBtnActionPerformed

        
        
        
        MessageFormat header=new MessageFormat(("Crédito :"+nombreCliente+"\n        "
                + "\ntotal :"+ TotalPagarCreditos));
MessageFormat footer=new MessageFormat("Page{0,number,integer}");
//MessageFormat total=new MessageFormat("Total :"+TotalPagar);
//MessageFormat direccion=new MessageFormat("Total :"+TotalPagar);
        try{

TableConsultaCreditCliente.print(JTable.PrintMode.FIT_WIDTH, header, footer);
//OutputStream file= new FileOutputstream(new File("C://impresiones//nombreCliente.pdf"));
    }catch(java.awt.print.PrinterException e){
System.err.format("Erreur d'impresion ",e.getMessage());
}     // TODO add your handling code here:
    }//GEN-LAST:event_PrintBtnActionPerformed

    private void btnCobrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCobrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCobrarMouseClicked

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed

        if (TableConsultaCreditCliente.getRowCount() > 0) {
            //original

            //if (!"".equals(txtPaga1.getText())) {
                ventanaCobrar cobrar = new ventanaCobrar();
                cobrar.setVisible(true);

                // String  info= lblEnviaTotal.getText();
                //ventanaCobrar.lblEnviaTotal.setText(info);
                // if (!"".equals(txtNombreClienteventa.getText())) {

                    // } else {
                    //   JOptionPane.showMessageDialog(null, "Debes buscar un cliente");
                    // }
                //} else {
                //JOptionPane.showMessageDialog(null, "Paga con $ ? ");
                // txtPaga1.requestFocus();
                //}
        } else {
            JOptionPane.showMessageDialog(null, "Noy productos en la venta");
            txtCodigoVenta.requestFocus();
        }
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void btnCobrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCobrarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCobrarKeyPressed

    private void btnGenerarVentaCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarVentaCreditActionPerformed
        if (TableConsultaCreditCliente.getRowCount() > 0) {
            //original

            if (!"".equals(txtNombreClienteventaCredit.getText())) {

                 // RegistrarVentaCreditos();// si guarda  el registro pero no guarda el total - vendedor .total. fecha
              //RegistrarDetalleCreditocliente();// id pro, cantidad,precio, id venta
              
                //ActualizarStock();
                LimpiarTableCredit();
                // LimpiarClienteventa();    se omitio  de momento
                // LimparVentaCredit();
                // LimpiarCobro();
                txtNombreClienteventaCredit.requestFocus();

                JOptionPane.showMessageDialog(null, "Registro exitoso");

            } else {
                JOptionPane.showMessageDialog(null, "Debes buscar un cliente");
                txtRucVentaCredit2.requestFocus();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Noy productos en la venta");
        }                  // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarVentaCreditActionPerformed

    private void txtRucVentaCredit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRucVentaCredit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucVentaCredit2ActionPerformed

    private void txtRucVentaCredit2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucVentaCredit2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //original
            if (!"".equals(txtRucVentaCredit2.getText())) {

                int dni = Integer.parseInt(txtRucVentaCredit2.getText());
                cl = client.Buscarcliente(dni);

                if (cl.getNombre() != null) {
                    txtNombreClienteventaCredit.setText("" + cl.getNombre());
                    //original

                    txtIdCV.setText("" + cl.getId());
                   
                } else {
                    txtRucVentaCredit2.setText("");
                    JOptionPane.showMessageDialog(null, "El cliente no existe");
                }

            }

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucVentaCredit2KeyPressed

    private void txtRucVentaCredit2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucVentaCredit2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucVentaCredit2KeyReleased

    private void txtRucVentaCredit2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucVentaCredit2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucVentaCredit2KeyTyped

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
   
    
        modelo = (DefaultTableModel) TableConsultaCreditCliente.getModel();
        modelo.removeRow(TableConsultaCreditCliente.getSelectedRow());
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCreditoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCreditoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCreditoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCreditoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaCreditoCliente().setVisible(true);
            }
        });
    }

  
  //suma las filas de la tabla venta
   public void TotalPagarX() {
        TotalPagarCreditos = 0.00;
        int numFila = TableConsultaCreditCliente.getRowCount();
        for (int i = 0; i < numFila; i++) {
            double cal = Double.parseDouble(String.valueOf(TableConsultaCreditCliente.getModel().getValueAt(i, 3)));
            
            TotalPagarCreditos = TotalPagarCreditos + cal;
        }
        lblEnviaTotalCredit.setText(String.format("%.2f", TotalPagarCreditos));
    }
   
  
    
     public void EnterBusqueda() {
           int  FilaSeleccionada=TableConsultaCreditCliente.getSelectedRow();
           if(FilaSeleccionada>=0){
 
        DefaultTableModel modelo=(DefaultTableModel)TableVenta.getModel();
           // envia los datos de tabla venta 
                  String Object[]=new String[5];
          
            Object[0]=TableConsultaCreditCliente.getValueAt(FilaSeleccionada,0).toString(); //id tabla venta
            Object[1]=TableConsultaCreditCliente.getValueAt(FilaSeleccionada,2).toString();
            Object[2]=txtCantidadVenta.getText().trim(); //cantida;
            Object[3]=TableConsultaCreditCliente.getValueAt(FilaSeleccionada,4).toString();
           Object[4]=TableConsultaCreditCliente.getValueAt(FilaSeleccionada,4).toString();
                 Object[4]=TableConsultaCreditCliente.getValueAt(FilaSeleccionada,4).toString();
      modelo.addRow(Object);
  
  } 
           this.dispose();
       
   jTabbedPane1.setSelectedIndex(0);    
       } 
     
   
       public void listar(){
       DefaultTableModel modelo=new DefaultTableModel();
       Connection nuevaConexion=null;
       
       
      //el trim sirve para remover espacios
         String cadena = txtBuscar2.getText().trim();
    String sql = "Select * from detalle_creditocliente where dni   like'"+"%"+cadena+"%' OR nombre  like'"+"%"+cadena+"%' OR precio  like'"+"%"+cadena+"%' OR fecha  like'"+"%"+cadena+"%'  ORDER BY `detalle_creditocliente`.`id` ASC" ;
   
      try{
          con = cn.getConnection();
            ps = con.prepareStatement(sql);
           
           
       Class.forName("com.mysql.cj.jdbc.Driver");
        String myBD = "jdbc:mysql://localhost:3306/puntedeventa-refresqueriaaixa?serverTimezone=UTC";
       nuevaConexion=(Connection)DriverManager.getConnection(myBD, "root", "");
       
       Statement s= nuevaConexion.createStatement();
       ResultSet rs=s.executeQuery(sql); 
       modelo.setColumnIdentifiers(new Object[]{"id_pro","nombre","cantidad","precio","fecha"});
       // modelo.setColumnIdentifiers(new Object[]{"dni"});
       while (rs.next())
       {
         modelo.addRow(new Object[]{
          
              rs.getString("id_pro"),
               rs.getString("nombre"),
               rs.getString("cantidad"),
               rs.getString("precio"),
                rs.getString("fecha")});  

      
       }
       //ancho de columnas
       TableConsultaCreditCliente.setModel(modelo);
          TableConsultaCreditCliente.getColumnModel().getColumn(0).setPreferredWidth(50); 
         TableConsultaCreditCliente.getColumnModel().getColumn(0).setResizable(false); 
           TableConsultaCreditCliente.getColumnModel().getColumn(1).setPreferredWidth(500); 
         TableConsultaCreditCliente.getColumnModel().getColumn(1).setResizable(false);
           TableConsultaCreditCliente.getColumnModel().getColumn(2).setPreferredWidth(30); 
         TableConsultaCreditCliente.getColumnModel().getColumn(2).setResizable(false);
          TableConsultaCreditCliente.getColumnModel().getColumn(3).setPreferredWidth(100); 
         TableConsultaCreditCliente.getColumnModel().getColumn(3).setResizable(false);
              TableConsultaCreditCliente.getColumnModel().getColumn(4).setPreferredWidth(140); 
         TableConsultaCreditCliente.getColumnModel().getColumn(4).setResizable(false);
         
         
         //alto de filas
          TableConsultaCreditCliente.setRowHeight(30);
       }catch(Exception e){
       JOptionPane.showMessageDialog(null,"No se a seleccionado alguna fila");
       }
    } 
         private void RegistrarVentaCreditos() {
        int cliente = Integer.parseInt(txtIdCV.getText());
       
         String vendedor = LabelVendedor.getText();
       double monto = TotalPagarCreditos;
      v.setCliente(cliente);
      //   v.setProducto(producto);
        v.setVendedor(vendedor);
        v.setTotal(monto);
        v.setFecha(fechaActual);
        Vdao.RegistrarVenta(v);
    }
       
       
       
       
      //private void RegistrarDetalleCreditocliente() {
       //     int id = Vdao.IdVenta();
       // for (int i = 0; i < TableConsultaCreditCliente.getRowCount(); i++) {
       //     int id_pro = Integer.parseInt(TableConsultaCreditCliente.getValueAt(i, 0).toString());
       //     int cant = Integer.parseInt(TableConsultaCreditCliente.getValueAt(i, 2).toString());
       //     double precio = Double.parseDouble(TableConsultaCreditCliente.getValueAt(i, 3).toString());
       //     Dv.setId_pro(id_pro);
       //     Dv.setCantidad(cant);
       //     Dv.setPrecio(precio);
       //     Dv.setId(id);
       //     Vdao.RegistrarDetalle(Dv);

       // }
       // int cliente = Integer.parseInt(txtIdCV.getText());
       // Vdao.pdfV(id, cliente, TotalPagarCreditos, LabelVendedor.getText());
       // }
       private void LimpiarTableCredit() {
        tmp = (DefaultTableModel) TableConsultaCreditCliente.getModel();
        int fila = TableConsultaCreditCliente.getRowCount();
        for (int i = 0; i < fila; i++) {
            tmp.removeRow(0);
        }
    }
      
        private void EliminarClienteCredito() {
      if (!"".equals(txtRucVentaCredit2.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar");
            if (pregunta == 0) {
                int dni = Integer.parseInt(txtRucVentaCredit2.getText());
                Vdao.EliminarClienteCredito(dni);
                //LimpiarTable();
                //LimpiarCliente();
                //ListarCliente();
            }
        }}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LabelVendedor;
    private javax.swing.JButton PrintBtn;
    public static javax.swing.JTable TableConsultaCreditCliente;
    public static javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerarVentaCredit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JScrollPane jScrollPane8;
    public static javax.swing.JLabel lblEnviaTotalCredit;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JTextField txtBuscar2;
    private javax.swing.JTextField txtCantidadVenta;
    public static javax.swing.JTextField txtIdCV;
    public static javax.swing.JTextField txtNombreClienteventaCredit;
    public static javax.swing.JTextField txtRucVentaCredit2;
    // End of variables declaration//GEN-END:variables
}
