/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Cliente;
import Modelo.ClienteDao;
import Modelo.Conexion;
import Modelo.Detalle;
import Modelo.Productos;
import Modelo.ProductosDao;
import Modelo.Venta;
import Modelo.VentaDao;
import static Vista.Sistema.LabelVendedor;
import static Vista.Sistema.TableCreditClient;
import static Vista.Sistema.TableVenta;
import static Vista.Sistema.jTabbedPane1;
import static Vista.Sistema.txtCodigoPro;
import static Vista.Sistema.txtCodigoVenta;
import static Vista.Sistema.txtCodigoVentaCreditClient;
import static Vista.Sistema.txtIdCV;
import static Vista.Sistema.txtNombreClienteventaCredit;
import static Vista.Sistema.txtRucVentaCredit;
import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author vic
 */
public class ConsultaCreditoCliente extends javax.swing.JFrame {
  
    
     Conexion con1 =new Conexion ();
    Connection conet;
   
   
    Statement  st;
   
    
    
    
    
    private int dato;
     private String nombreCliente;
      Date fechaVenta = new Date();
     String fechaActual = new SimpleDateFormat("dd/MM/yyyy").format(fechaVenta);
    
    
        Connection con;
    Conexion cn = new Conexion();
    PreparedStatement ps;
    ResultSet rs;
    DefaultTableModel modelo = new DefaultTableModel(); 
     Cliente cl = new Cliente();
    ClienteDao client = new ClienteDao();
    VentaDao Vdao = new VentaDao();
      Detalle Dv = new Detalle();
          Venta v = new Venta();
    DefaultTableModel tmp = new DefaultTableModel();
  //TableRowSorter<DefaultTableModel>sorter;
  
   Productos pro = new Productos();
    ProductosDao proDao = new ProductosDao();
     String mayus;
      double TotalPagar = 0.00;
          double TotalpagarCredit= 0.00;
            double TotalPagarCreditos= 0.00;
    /**
     * Creates new form FrmBusqueda
     */
      
    public ConsultaCreditoCliente() {
        
        initComponents();
                //listar(); 
                TotalPagarX();

          //ListarProductos4();
           txtBuscar3.requestFocus();
          this.setLocationRelativeTo(null);
           txtCantidadVenta.setVisible(false);
           jLabel5.setVisible(false);
           
           //boton buscar
           jLabel52.setVisible(false);
           
               txtBuscar3.setVisible(false);
               
               txtRucVentaCredit.setVisible(false);
               txtNombreClienteventaCredit.setVisible(false);
              
             jLabel59.setVisible(false);
                       jLabel58.setVisible(false);
                       txtIdCV.setVisible(false);
                       
                       
                       //boton eliminar
                       btnEliminarventaCredit.setVisible(true);
                               txtEliminarRegistro.setVisible(true);
    }
public void sedDato(int dato,String nombreCliente){


this.dato=dato;
this.nombreCliente=nombreCliente;

txtBuscar3.setText(dato+"");
lblNombreCliente.setText(nombreCliente);
txtRucVentaCredit.setText(dato+"");


} 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        TableConsultaCreditCliente = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtCantidadVenta = new javax.swing.JTextField();
        txtBuscar3 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        lblEnviaTotalCredit = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PrintBtn = new javax.swing.JButton();
        LabelVendedor = new javax.swing.JLabel();
        txtIdCV = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        txtRucVentaCredit = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        txtNombreClienteventaCredit = new javax.swing.JTextField();
        btnCobrarCredito = new javax.swing.JButton();
        btnEliminarventaCredit = new javax.swing.JButton();
        txtStockDisponible2 = new javax.swing.JTextField();
        txtEliminarRegistro = new javax.swing.JTextField();
        jlanelid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("formKeyReleased"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        TableConsultaCreditCliente.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        TableConsultaCreditCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CODIGO", "DESCRIPCIÓN", "CANTIDAD", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableConsultaCreditCliente.setRowHeight(25);
        TableConsultaCreditCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableConsultaCreditClienteMouseClicked(evt);
            }
        });
        TableConsultaCreditCliente.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                TableConsultaCreditClienteCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        TableConsultaCreditCliente.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TableConsultaCreditClientePropertyChange(evt);
            }
        });
        TableConsultaCreditCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TableConsultaCreditClienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TableConsultaCreditClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TableConsultaCreditClienteKeyTyped(evt);
            }
        });
        jScrollPane8.setViewportView(TableConsultaCreditCliente);
        if (TableConsultaCreditCliente.getColumnModel().getColumnCount() > 0) {
            TableConsultaCreditCliente.getColumnModel().getColumn(0).setMinWidth(10);
            TableConsultaCreditCliente.getColumnModel().getColumn(0).setPreferredWidth(50);
            TableConsultaCreditCliente.getColumnModel().getColumn(0).setMaxWidth(50);
            TableConsultaCreditCliente.getColumnModel().getColumn(1).setMinWidth(50);
            TableConsultaCreditCliente.getColumnModel().getColumn(1).setPreferredWidth(100);
            TableConsultaCreditCliente.getColumnModel().getColumn(1).setMaxWidth(60);
            TableConsultaCreditCliente.getColumnModel().getColumn(2).setResizable(false);
            TableConsultaCreditCliente.getColumnModel().getColumn(2).setPreferredWidth(200);
            TableConsultaCreditCliente.getColumnModel().getColumn(3).setMinWidth(20);
            TableConsultaCreditCliente.getColumnModel().getColumn(3).setPreferredWidth(50);
            TableConsultaCreditCliente.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Cant");

        txtCantidadVenta.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCantidadVenta.setText("1");
        txtCantidadVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadVentaActionPerformed(evt);
            }
        });
        txtCantidadVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadVentaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadVentaKeyTyped(evt);
            }
        });

        txtBuscar3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtBuscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar3ActionPerformed(evt);
            }
        });
        txtBuscar3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscar3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscar3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscar3KeyTyped(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(51, 51, 255));
        jLabel52.setText("Buscar ");

        jLabel60.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/money.png"))); // NOI18N
        jLabel60.setText("Total :");

        lblEnviaTotalCredit.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        lblEnviaTotalCredit.setForeground(new java.awt.Color(51, 51, 255));
        lblEnviaTotalCredit.setText("-----");

        lblNombreCliente.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNombreCliente.setForeground(new java.awt.Color(255, 0, 0));
        lblNombreCliente.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CREDITO:");

        PrintBtn.setText("PDF Compartir");
        PrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBtnActionPerformed(evt);
            }
        });

        LabelVendedor.setForeground(new java.awt.Color(255, 255, 255));
        LabelVendedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelVendedor.setText("Vida Informatico");

        txtIdCV.setText("1");

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel58.setText("ID");

        txtRucVentaCredit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtRucVentaCredit.setText("1");
        txtRucVentaCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRucVentaCreditActionPerformed(evt);
            }
        });
        txtRucVentaCredit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRucVentaCreditKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRucVentaCreditKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRucVentaCreditKeyTyped(evt);
            }
        });

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel59.setText("Cliente:");

        txtNombreClienteventaCredit.setEditable(false);
        txtNombreClienteventaCredit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtNombreClienteventaCredit.setForeground(new java.awt.Color(51, 51, 255));
        txtNombreClienteventaCredit.setText("DEFAULT");

        btnCobrarCredito.setText("cobrar");
        btnCobrarCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarCreditoActionPerformed(evt);
            }
        });

        btnEliminarventaCredit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminarventaCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarventaCreditActionPerformed(evt);
            }
        });

        txtStockDisponible2.setEditable(false);

        txtEliminarRegistro.setEditable(false);

        jlanelid.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlanelid.setText("id :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIdCV, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(txtCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel58)
                        .addGap(16, 16, 16)
                        .addComponent(txtRucVentaCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel59)
                        .addGap(31, 31, 31)
                        .addComponent(txtNombreClienteventaCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addGap(28, 28, 28)
                                .addComponent(txtBuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(lblNombreCliente)
                                .addGap(193, 193, 193)
                                .addComponent(PrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txtStockDisponible2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblEnviaTotalCredit))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(btnCobrarCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarventaCredit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlanelid, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEliminarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIdCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(715, 715, 715))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelVendedor)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtBuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(lblNombreCliente))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel52)
                                        .addGap(33, 33, 33))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel58)
                                    .addComponent(jLabel5)
                                    .addComponent(txtCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtRucVentaCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel59))
                            .addComponent(txtNombreClienteventaCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarventaCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtEliminarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlanelid)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStockDisponible2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel60)
                            .addComponent(lblEnviaTotalCredit))
                        .addGap(79, 79, 79)
                        .addComponent(btnCobrarCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(154, 154, 154))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableConsultaCreditClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableConsultaCreditClienteMouseClicked
int fila = TableConsultaCreditCliente.rowAtPoint(evt.getPoint());
        txtEliminarRegistro.setText(TableConsultaCreditCliente.getValueAt(fila, 0).toString());
     
    }//GEN-LAST:event_TableConsultaCreditClienteMouseClicked

    private void TableConsultaCreditClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableConsultaCreditClienteKeyPressed



        
        //este codigog desactiva la accion enter por defefault
        JTable jMyTable = new JTable();
jMyTable.addKeyListener(new java.awt.event.KeyAdapter() {
     public void keyPressed(java.awt.event.KeyEvent evt) {
         TableConsultaCreditClienteKeyPressed(evt);
     }
 });
        
        if(evt.getKeyCode() == evt.VK_ENTER){
         evt.consume();
         EnterBusqueda();
            txtCodigoVenta.requestFocus();
     }


    }//GEN-LAST:event_TableConsultaCreditClienteKeyPressed

    
       
    
    
    private void TableConsultaCreditClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableConsultaCreditClienteKeyTyped

 //if(evt.getKeyCode() == evt.VK_ENTER){
   //      evt.consume();
     //}
int fila = TableConsultaCreditCliente.getSelectedRow();
      if(fila == -1){
          txtBuscar3.requestFocus();
     JOptionPane.showMessageDialog(null,"No se selecciono ningna fila");
        }else{
          // EnterBusqueda();      
        }            // TODO add your handling code here:
  
      
    }//GEN-LAST:event_TableConsultaCreditClienteKeyTyped

    private void TableConsultaCreditClientePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TableConsultaCreditClientePropertyChange
      // TODO add your handling code here:
    }//GEN-LAST:event_TableConsultaCreditClientePropertyChange

    private void TableConsultaCreditClienteCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TableConsultaCreditClienteCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TableConsultaCreditClienteCaretPositionChanged

    private void TableConsultaCreditClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableConsultaCreditClienteKeyReleased
       // TODO add your handling code here:
    }//GEN-LAST:event_TableConsultaCreditClienteKeyReleased

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

              // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
       // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
listar();   
TotalPagarX();
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void PrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBtnActionPerformed

        
        
        
        MessageFormat header=new MessageFormat(("Crédito :"+nombreCliente+"\n        "
                + "\ntotal :"+ TotalPagarCreditos));
MessageFormat footer=new MessageFormat("Page{0,number,integer}");
//MessageFormat total=new MessageFormat("Total :"+TotalPagar);
//MessageFormat direccion=new MessageFormat("Total :"+TotalPagar);
        try{

TableConsultaCreditCliente.print(JTable.PrintMode.FIT_WIDTH, header, footer);
//OutputStream file= new FileOutputstream(new File("C://impresiones//nombreCliente.pdf"));
    }catch(java.awt.print.PrinterException e){
System.err.format("Erreur d'impresion ",e.getMessage());
}     // TODO add your handling code here:
    }//GEN-LAST:event_PrintBtnActionPerformed

    private void txtBuscar3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscar3KeyTyped

        KeyboardFocusManager kb = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        kb.addKeyEventPostProcessor(new KeyEventPostProcessor(){
            public boolean postProcessKeyEvent(KeyEvent e){
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE && this != null){
                    System.out.println("probando...");
                    dispose();
                    return false;
                }
                return true;
            }
        });

    }//GEN-LAST:event_txtBuscar3KeyTyped

    private void txtBuscar3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscar3KeyReleased

        // if (!"".equals(txtBuscar.getText())) {

            //}else

        //{
            //     }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar3KeyReleased

    private void txtBuscar3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscar3KeyPressed
        this.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar3KeyPressed

    private void txtBuscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar3ActionPerformed

    private void btnCobrarCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarCreditoActionPerformed

       if (TableConsultaCreditCliente.getRowCount() > 0) {
           
             ventanaCobrarCredito cobrar = new ventanaCobrarCredito();
             cobrar.sedDato(Integer.parseInt(txtRucVentaCredit.getText()));
        cobrar.setVisible(true);
     
       } else {
            JOptionPane.showMessageDialog(null, "Noy productos en la venta");
          
       }
    }//GEN-LAST:event_btnCobrarCreditoActionPerformed

    private void txtCantidadVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadVentaKeyTyped
        // TODO add your handling code here:
        //   event.numberKeyPress(evt);
    }//GEN-LAST:event_txtCantidadVentaKeyTyped

    private void txtCantidadVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadVentaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadVentaKeyPressed

    private void txtCantidadVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadVentaActionPerformed

    private void txtRucVentaCreditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucVentaCreditKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucVentaCreditKeyTyped

    private void txtRucVentaCreditKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucVentaCreditKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucVentaCreditKeyReleased

    private void txtRucVentaCreditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucVentaCreditKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //original
            if (!"".equals(txtRucVentaCredit.getText())) {

                int dni = Integer.parseInt(txtRucVentaCredit.getText());
                cl = client.Buscarcliente(dni);

                if (cl.getNombre() != null) {
                    txtNombreClienteventaCredit.setText("" + cl.getNombre());
                    //original

                    txtIdCV.setText("" + cl.getId());

                } else {
                    txtRucVentaCredit.setText("");
                    JOptionPane.showMessageDialog(null, "El cliente no existe");
                }

            }

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucVentaCreditKeyPressed

    private void txtRucVentaCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRucVentaCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucVentaCreditActionPerformed

    private void btnEliminarventaCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarventaCreditActionPerformed
       if (TableConsultaCreditCliente.getRowCount() > 0) { 
                 
      EliminarRegistro();
     
            
      } else {
            JOptionPane.showMessageDialog(null, "Noy productos en la venta");
            txtCodigoVenta.requestFocus();
             limpiarTabla();
       } 
    }//GEN-LAST:event_btnEliminarventaCreditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCreditoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCreditoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCreditoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCreditoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaCreditoCliente().setVisible(true);
            }
        });
    }

  
  //suma las filas de la tabla venta
   public void TotalPagarX() {
        TotalPagarCreditos = 0.00;
        int numFila = TableConsultaCreditCliente.getRowCount();
        for (int i = 0; i < numFila; i++) {
            double cal = Double.parseDouble(String.valueOf(TableConsultaCreditCliente.getModel().getValueAt(i, 5)));
            
            TotalPagarCreditos = TotalPagarCreditos + cal;
        }
        lblEnviaTotalCredit.setText(String.format("%.2f", TotalPagarCreditos));
    }
   
  
    
     public void EnterBusqueda() {
           int  FilaSeleccionada=TableConsultaCreditCliente.getSelectedRow();
           if(FilaSeleccionada>=0){
 
        DefaultTableModel modelo=(DefaultTableModel)TableVenta.getModel();
           // envia los datos de tabla venta 
                  String Object[]=new String[5];
          
            Object[0]=TableConsultaCreditCliente.getValueAt(FilaSeleccionada,0).toString(); //id tabla venta
            Object[1]=TableConsultaCreditCliente.getValueAt(FilaSeleccionada,2).toString();
            Object[2]=txtCantidadVenta.getText().trim(); //cantida;
            Object[3]=TableConsultaCreditCliente.getValueAt(FilaSeleccionada,4).toString();
           Object[4]=TableConsultaCreditCliente.getValueAt(FilaSeleccionada,4).toString();
                 Object[4]=TableConsultaCreditCliente.getValueAt(FilaSeleccionada,4).toString();
      modelo.addRow(Object);
  
  } 
           this.dispose();
       
   jTabbedPane1.setSelectedIndex(0);    
       } 
     
  public void listar() {
      // codigo en linea
   DefaultTableModel modelo = new DefaultTableModel();
  Connection nuevaConexion = null;
   // Mostrar el loader
  
  // El trim sirve para remover espacios
  String cadena = txtBuscar3.getText().trim();
  
  // Usamos parámetros para evitar inyecciones SQL y mejorar la eficiencia
  String sql = "SELECT * FROM detalle_creditocliente WHERE dni LIKE ? OR nombre LIKE ? OR precio LIKE ? OR total LIKE ? OR fecha LIKE ? ORDER BY id ASC";

  try {
      // Usamos una conexión ya establecida en linea hostinguer
      nuevaConexion = DriverManager.getConnection(  //es en linea
              "jdbc:mysql://193.203.166.21/u722149126_tienditaaixa?useSSL=false&serverTimezone=UTC&connectTimeout=10000", //es en linea
              
     "u722149126_victor", //es en linea
              "Lolo140516");//es en linea

      /*es localmente
     nuevaConexion = DriverManager.getConnection( // es localmente
    "jdbc:mysql://localhost:3306/puntedeventa-refresqueriaaixa?serverTimezone=UTC", // es localmente
    "root", ""// es localmente
);*/  //es localmente 
      // Preparamos la consulta
      PreparedStatement ps = nuevaConexion.prepareStatement(sql);
      
      // Creamos el término de búsqueda con los comodines '%'
      String searchTerm = "%" + cadena + "%";
      
      // Parametrizamos la consulta
      ps.setString(1, searchTerm);
      ps.setString(2, searchTerm);
      ps.setString(3, searchTerm);
      ps.setString(4, searchTerm);
      ps.setString(5, searchTerm);
      
      // Ejecutamos la consulta
      ResultSet rs = ps.executeQuery();
      
      // Configuramos las columnas de la tabla
      modelo.setColumnIdentifiers(new Object[]{"id", "id_pro", "nombre", "cantidad", "precio", "total", "fecha", "dni"});
      
      // Llenamos el modelo con los resultados de la consulta
      while (rs.next()) {
          modelo.addRow(new Object[]{
              rs.getString("id"),
              rs.getString("id_pro"),
              rs.getString("nombre"),
              rs.getString("cantidad"),
              rs.getString("precio"),
              rs.getString("total"),
              rs.getString("fecha"),
              rs.getString("dni")
          });
      }

      // Establecemos el modelo en la tabla y configuramos el tamaño de las columnas
      TableConsultaCreditCliente.setModel(modelo);
      TableConsultaCreditCliente.getColumnModel().getColumn(0).setPreferredWidth(0); 
      TableConsultaCreditCliente.getColumnModel().getColumn(0).setResizable(false); 
      TableConsultaCreditCliente.getColumnModel().getColumn(1).setPreferredWidth(0); 
      TableConsultaCreditCliente.getColumnModel().getColumn(1).setResizable(false);
      TableConsultaCreditCliente.getColumnModel().getColumn(2).setPreferredWidth(500); 
      TableConsultaCreditCliente.getColumnModel().getColumn(2).setResizable(false);
      TableConsultaCreditCliente.getColumnModel().getColumn(3).setPreferredWidth(80); 
      TableConsultaCreditCliente.getColumnModel().getColumn(3).setResizable(false);
      TableConsultaCreditCliente.getColumnModel().getColumn(4).setPreferredWidth(100); 
      TableConsultaCreditCliente.getColumnModel().getColumn(4).setResizable(false);
      TableConsultaCreditCliente.getColumnModel().getColumn(5).setPreferredWidth(80); 
      TableConsultaCreditCliente.getColumnModel().getColumn(5).setResizable(false);
      TableConsultaCreditCliente.getColumnModel().getColumn(6).setPreferredWidth(140); 
      TableConsultaCreditCliente.getColumnModel().getColumn(6).setResizable(false);
      TableConsultaCreditCliente.getColumnModel().getColumn(7).setPreferredWidth(80); 
      TableConsultaCreditCliente.getColumnModel().getColumn(7).setResizable(false);
      
      // Ajustamos la altura de las filas
      TableConsultaCreditCliente.setRowHeight(30);
      
  } catch (Exception e) {
      JOptionPane.showMessageDialog(null, "Error al cargar los productos: " + e.getMessage());
  } finally {
      try {
          if (nuevaConexion != null && !nuevaConexion.isClosed()) {
              nuevaConexion.close();
          }
      } catch (SQLException e) {
          e.printStackTrace();
      }
      
  }
}

     
         
      void EliminarRegistro(){
           
 Conexion con1=null;
    DefaultTableModel modelo=new DefaultTableModel();
  Connection nuevaConexion=null;
    if (!"".equals(txtEliminarRegistro.getText())) {
        
    }else{
       JOptionPane.showMessageDialog(null, "Selecciona una fila");
   }
    
    
    try{
         
          con = cn.getConnection();
      
     ps = con.prepareStatement("delete from  detalle_creditocliente  where  id=?");
         ps.setInt(1,Integer.parseInt(txtEliminarRegistro.getText()));
    
        int resultado=ps.executeUpdate();
        
           if(resultado>=0){
           JOptionPane.showMessageDialog(null,"Registro Eliminado");
           limpiarTabla();
           }else{
           JOptionPane.showMessageDialog(null," No se encuentra regitro");
                   }
        
          con.close();
         
     }catch (Exception e){
     System.err.println("Error:"+e);
     }     

        
      } 
         private void RegistrarVentaCreditos() {
    try {
        // Asegurarse de que el objeto v esté inicializado
        Venta v = new Venta();
        
        // Verificar que txtIdCV no esté vacío y que contenga un valor numérico
        String idTexto = txtIdCV.getText();
        if (idTexto.isEmpty()) {
            System.out.println("El ID del cliente no puede estar vacío.");
            return; // Salir del método si el ID está vacío
        }
        
        // Convertir el ID a un número entero
        int cliente = Integer.parseInt(idTexto);
        
        // Obtener los demás datos
        String vendedor = LabelVendedor.getText();
        double monto = TotalPagarCreditos; // Asegúrate de que esta variable esté definida y contenga un valor válido

        // Asignar los datos al objeto v
        v.setCliente(cliente);
        v.setVendedor(vendedor);
        v.setTotal(monto);
        
        // Asignar la fecha
        v.setFecha(fechaActual);

        // Registrar la venta
        Vdao.RegistrarVenta(v);
        
    } catch (NumberFormatException e) {
        System.out.println("Error al convertir el ID del cliente: " + e.getMessage());
    } catch (Exception e) {
        System.out.println("Error al registrar la venta: " + e.getMessage());
    }
}
       
       
       
       
   
       private void LimpiarTableCredit() {
        tmp = (DefaultTableModel) TableConsultaCreditCliente.getModel();
        int fila = TableConsultaCreditCliente.getRowCount();
        for (int i = 0; i < fila; i++) {
            tmp.removeRow(0);
        }
    }
    
      void limpiarTabla(){
      txtEliminarRegistro.setText("");   
for (int i=0; i <= TableConsultaCreditCliente.getRowCount(); i++){
    modelo.removeRow(i);
            i= i-1;
        
}   
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LabelVendedor;
    private javax.swing.JButton PrintBtn;
    public static javax.swing.JTable TableConsultaCreditCliente;
    private javax.swing.JButton btnCobrarCredito;
    private javax.swing.JButton btnEliminarventaCredit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel jlanelid;
    public static javax.swing.JLabel lblEnviaTotalCredit;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JTextField txtBuscar3;
    private javax.swing.JTextField txtCantidadVenta;
    private javax.swing.JTextField txtEliminarRegistro;
    public static javax.swing.JTextField txtIdCV;
    public static javax.swing.JTextField txtNombreClienteventaCredit;
    public static javax.swing.JTextField txtRucVentaCredit;
    private javax.swing.JTextField txtStockDisponible2;
    // End of variables declaration//GEN-END:variables
}
